"""
METRICS ENGINE
All financial metric calculations live in app.calculator.
This module re-exports them for engine usage.
"""

from app.calculator import (
    safe_div,
    calc_nopat,
    calc_invested_capital,
    calc_roic,
    calc_incremental_roic,
    calc_ebit,
    calc_gross_margin,
    calc_ebit_margin,
    calc_roe,
    calc_asset_turnover,
    calc_operating_leverage,
    calc_fcf,
    calc_cfo_to_ebitda,
    calc_fcf_to_net_income,
    calc_fcf_margin,
    calc_cash_conversion_cycle,
    calc_working_capital_change,
    calc_net_debt,
    calc_net_debt_to_ebitda,
    calc_interest_coverage,
    calc_current_ratio,
    calc_quick_ratio,
    calc_cagr,
    calc_ev_to_ebitda,
    calc_pe_ratio,
    calc_fcf_yield,
    calc_altman_z,
)

__all__ = [
    "safe_div",
    "calc_nopat",
    "calc_invested_capital",
    "calc_roic",
    "calc_incremental_roic",
    "calc_ebit",
    "calc_gross_margin",
    "calc_ebit_margin",
    "calc_roe",
    "calc_asset_turnover",
    "calc_operating_leverage",
    "calc_fcf",
    "calc_cfo_to_ebitda",
    "calc_fcf_to_net_income",
    "calc_fcf_margin",
    "calc_cash_conversion_cycle",
    "calc_working_capital_change",
    "calc_net_debt",
    "calc_net_debt_to_ebitda",
    "calc_interest_coverage",
    "calc_current_ratio",
    "calc_quick_ratio",
    "calc_cagr",
    "calc_ev_to_ebitda",
    "calc_pe_ratio",
    "calc_fcf_yield",
    "calc_altman_z",
]
